webas_webas_homepage:
    path:     /
    defaults: { _controller: WebasWebasBundle:Default:index }

webas_webas_show_post:
    path:     /post/{post}
    defaults: { _controller: WebasWebasBundle:Default:showPost }

webas_webas_create_post:
    path:     /create_post
    defaults: { _controller: WebasWebasBundle:Default:createPost }
