parameters:
#    webas_webas.example.class: Webas\WebasBundle\Example

services:
#    webas_webas.example:
#        class: %webas_webas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
